<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Ticket_vkr.UI</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.1" />
    <PackageReference Include="PDFsharp" Version="6.1.1" />
    <PackageReference Include="QuestPDF" Version="2025.1.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Settings\" />
  </ItemGroup>

</Project>
